### PR TITLE
Hide <dfn> self-links on mobile

### PR DESCRIPTION
**Pull request by domenic**
See https://github.com/tabatkins/bikeshed/issues/893 for context.

### CODE REVIEW

**Comment by annevk** [comment]
Seems fine, ta!

**Comment by domenic** [comment]
I guess we can try to use [the hover media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover) in combination with `@supports` or something?

**Comment by zcorpan** [comment]
No need for `@supports` I think. I guess that works, or my suggestion in the issue to make it not overflow...

**Comment by domenic** [comment]
Well we'd want to still hide it in mobile Gecko, so if you don't support that media query we'd use a width-based one.

**Comment by domenic** [comment]
After thinking this through, I went with a slightly different strategy:

- Shrink the size of dfn self-links on small viewports, as @zcorpan suggested. This guarantees no horizontal scrollbars no matter what, which I think is a baseline requirement.
- Hide dfn self-links if hover is not supported by the primary input device. (See [this article](https://dev.opera.com/articles/media-features/) for more info.) Where supported (i.e. mobile Blink and presumably mobile Edge) this avoids the slightly ugly flash I see in the emulator where first the self-link pops up but then dfn.js pops up over it, as a minor enhancement.

**Comment by tabatkins** [comment]
Note that the suppression isn't needed if you're using Bikeshed-generated dfn panels, as it generates *either* a self-link *or* a dfn panel, never both.  A better fix would be to make your panel-generating script do the same, and just remove the self-link if it generates a panel.

**Pull request merged**
