### PR TITLE
Use 'hyphens' for small viewports

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by domenic** [comment]
Before/after screenshot? :)

**Comment by zcorpan** [comment]
screenshot_20161110-221438
screenshot_20161110-221427

Ignore the red filter. 😊 This is not with the spec's exact styles; couldn't figure out how to manipulate the DOM in Firefox for Android, so whipped something up with live dom viewer.

**Comment by annevk** [comment]
It looks better, but for single-page, presumably this is also worse perf-wise, no?

(We might want to look into perf in general I think. Folks have suggested there are some things we could to make it better, even though we've mostly argued that browsers should just improve.)

**Comment by zcorpan** [comment]
Load times using `performance.now()` in a `script` at the top and `<body onload="alert(Math.round(performance.now() - startTime))">`

Firefox:
with hyphens: 16098, 17287
without hyphens: 13940, 13908

Safari:
with hyphens: 8163, 8664
without hyphens: 8365, 7237

I suppose it is a perf regression with hyphens. What do people think? Do people read the single-page with small viewports? It would be possible to only apply the style to multipage.

I agree we should look into perf.

**Comment by zcorpan** [comment]
I found that Safari needs `-webkit-` prefix.

I have a version of the spec without any scripts or styles or external resources, where enabling -webkit-hyphens does not seem to regress loading performance in Safari. But hyphens does regress performance by 1-2 seconds in Firefox.

Let's punt on this until hyphens is more widely implemented (unprefixed) and its perf is not an issue.

**Pull request closed without merging**
