### PR TITLE
Exclude bikeshed's Index and IDL Index

### PR DESCRIPTION
**Pull request by zcorpan**
Also always run initDfn() since it currently runs on HTML's multipage anyway.

r? @annevk

### CODE REVIEW

**Comment by annevk** [comment]
Is `closest()` support somewhat widespread now?

**Comment by annevk** [comment]
Commit message should probably mention dfn.js. Thought this was a larger change of sorts...

**Comment by zcorpan** [comment]
It's... not supported in Edge.
http://caniuse.com/#search=closest

**Comment by zcorpan** [comment]
Feature request for Edge at https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10119510-element-closest

Can we merge this anyway? Alternatively we could add no-backref classes to bikeshed's output...

**Comment by annevk** [comment]
Fine with me.

**Pull request merged**
