### PR TITLE
Import specification.css from https://whatwg.org/style/specification

### PR DESCRIPTION
**Pull request by foolip**
Trailing whitespace stripped, no other changes.

### CODE REVIEW

**Comment by foolip** [comment]
Let's bring this under version control, as a first step to experimenting with changes in https://github.com/whatwg/html/issues/620

**Comment by annevk** [comment]
s/specification/standard/?

**Comment by annevk** [comment]
Or maybe it doesn't matter, the domain name says "spec" already anyway.

**Comment by annevk** [comment]
Anyway, LGTM.

**Comment by foolip** [comment]
Mid-air collision, you get to pick :)

**Pull request merged**
