### PR TITLE
Add fonts for encoding visualizations.

### PR DESCRIPTION
**Pull request by hsivonen**
Fonts for upcoming encoding visualizations discussed in the [encoding issue about euc-kr structure](https://github.com/whatwg/encoding/issues/78).

r? @annevk

### CODE REVIEW

**Comment by annevk** [comment]
LGTM. Perhaps we should add to fonts/README.md why you would use these fonts, but I don't want to block on that if you're not up for it.

**Comment by annevk** [comment]
The only nit I have by the way is that if you want to commit this, please exclude the trailing dot. We use the first line of the commit message as a title.

**Comment by hsivonen** [comment]
Is it OK now?

**Comment by annevk** [comment]
Yeah that's fine. I actually meant a bit more general (you might want to use these fonts for X), but let's land it. Thanks!

**Pull request merged**
