### PR TITLE
Make multipage link in single-page HTML spec stand out

### PR DESCRIPTION
**Pull request by zcorpan**
multipage-link

### CODE REVIEW

**Comment by foolip** [comment]
Will it really overlap the other boxes like in the screenshot?

**Comment by zcorpan** [comment]
Yes. Is that a problem?

**Comment by foolip** [comment]
I do think it looks a bit like a mistake. Maybe we can match the header style of other WHATWG specs, like https://dom.spec.whatwg.org/? Then making multi-page stand out would be much easier, maybe a box or something?

@annevk @domenic?

**Comment by domenic** [comment]
I like the current header style and don't much want to re-do it.

Maybe we can just not emphasize the multipage? Or, emphasize it in this fashion while the page loads, but not when it's finished? I dunno.

**Comment by zcorpan** [comment]
Removing this style onload or even after some timeout sounds like a good idea.

**Comment by zcorpan** [comment]
Made it go away after 10s. PTAL

**Pull request merged**
